schemaVersion: '2.0.0'

fileExistenceTests:
  - name: 'Node.js Executable'
    path: '/usr/bin/node'
    shouldExist: true
  - name: 'NPM Executable'
    path: '/usr/bin/npm'
    shouldExist: true
  - name: 'Playwright Directory'
    path: '/ms-playwright'
    shouldExist: true
  - name: 'Global npm packages directory'
    path: '/usr/local/lib/node_modules'
    shouldExist: true

commandTests:
  - name: 'Node.js Version'
    command: 'node'
    args: ['--version']
    expectedOutput: ['v.*']
  - name: 'NPM Version'
    command: 'npm'
    args: ['--version']
    expectedOutput: ['.*']
  - name: 'Playwright CLI'
    command: 'npx'
    args: ['playwright', '--version']
    expectedOutput: ['Version .*']
  - name: 'Jest Availability'
    command: 'jest'
    args: ['--version']
    expectedOutput: ['.*']
  - name: 'TypeScript Availability'
    command: 'tsc'
    args: ['--version']
    expectedOutput: ['Version .*']

metadataTest:
  envVars: []
  exposedPorts: []
  volumes: []
  workdir: '' 