FROM mcr.microsoft.com/playwright:v1.49.1-noble

ARG DEBIAN_FRONTEND=noninteractive
ARG PLAYWRIGHT_VERSION=1.49.1

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# hadolint ignore=DL3008
RUN apt-get update && \
  apt-get install --no-install-recommends -y \
    default-jdk \
    jq=1.7.1-3build1 \
    && \
  rm -rf /var/lib/apt/lists/* 

RUN npm install -g corepack@0.24.1 && \
    corepack enable pnpm && \
    corepack enable yarn

COPY package.json /ms-playwright-agent/package.json

WORKDIR /ms-playwright-agent

# hadolint ignore=DL3016,SC2046
RUN npm install -g $(jq -r '.dependencies | to_entries | map(.key + "@" + .value) | join(" ")' package.json) && \
  rm package.json

# The ADO agent does not support non-root users
# USER pwuser
